### ISSUE TITLE
Remove inputs

### ISSUE THREAD

**Issue by KirillTregubov** [50SACINMYSOCIDGAF/AdventOfCode2024#1]
Hey! Congrats on achieving a high rank on the leaderboard. I was just browsing repositories and noticed that you included your inputs. According to the [AoC About page](https://adventofcode.com/2024/about):

> Can I copy/redistribute part of Advent of Code? Please don't. Advent of Code is free to use, not free to copy. If you're posting a code repository somewhere, please don't include parts of Advent of Code like the puzzle text or your inputs. If you're making a website, please don't make it look like Advent of Code or name it something similar.

I suggest removing your inputs and not posting them in the future. Cheers, and good luck with the rest of the advent!

**Comment by 50SACINMYSOCIDGAF** [comment]
Ah! my apologies, I did not realize inputs were included under this. Will remove. Thank you, have a good day
